name: Test and upload package

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
      - '!v*-dev'
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm test

  upload:
    runs-on: ubuntu-latest
    needs: [test]
    if: github.repository == 'corelight/communityid-js' && github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v3
      - name: Check release version
        # This fails e.g. if package.json's version contains a dev commits
        # suffix, since we don't want to push these to PyPI. Accepts two- and
        # three-component version numbers (e.g. 1.0 and 1.0.1).
        run: |
          node -p "require('./package.json').version" | grep -E -x '[0-9]+\.[0-9]+(\.[0-9]+)?'
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
      - name: Publish NPM package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
